<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-0I845IR8" failures="4" tests="9" name="TestCase003" time="0.024" errors="0" timestamp="2024-08-16T14:44:18 IST">
  <testcase classname="Assesertion_Demo.TestClass01" name="testMethod01" time="0.001"/>
  <testcase classname="Assesertion_Demo.TestClass01" name="testMethod02" time="0.002">
    <failure type="java.lang.AssertionError" message="This test will pass only when provided condition become false expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: This test will pass only when provided condition become false expected [false] but found [true]
at Assesertion_Demo.TestClass01.testMethod02(TestClass01.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testMethod02 -->
  <testcase classname="Assesertion_Demo.TestClass01" name="testMethod03" time="0.001">
    <failure type="java.lang.AssertionError" message="This test will pass only when both Actual &amp;amp; Expected matches expected [hello] but found [Hello]">
      <![CDATA[java.lang.AssertionError: This test will pass only when both Actual & Expected matches expected [hello] but found [Hello]
at Assesertion_Demo.TestClass01.testMethod03(TestClass01.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testMethod03 -->
  <testcase classname="Assesertion_Demo.TestClass01" name="testMethod04" time="0.001"/>
  <testcase classname="Assesertion_Demo.TestClass01" name="testMethod05" time="0.002">
    <failure type="java.lang.AssertionError" message="This test will pass only when provided object is null expected [null] but found [hello]">
      <![CDATA[java.lang.AssertionError: This test will pass only when provided object is null expected [null] but found [hello]
at Assesertion_Demo.TestClass01.testMethod05(TestClass01.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testMethod05 -->
  <testcase classname="Assesertion_Demo.TestClass01" name="testMethod06" time="0.001"/>
  <testcase classname="Assesertion_Demo.TestClass01" name="testMethod07" time="0.001"/>
  <testcase classname="Assesertion_Demo.TestClass01" name="testMethod08" time="0.001"/>
  <testcase classname="Assesertion_Demo.TestClass01" name="testMethod09" time="0.0">
    <failure type="java.lang.AssertionError" message="This method is used to fail the particular test case intentionally">
      <![CDATA[java.lang.AssertionError: This method is used to fail the particular test case intentionally
at Assesertion_Demo.TestClass01.testMethod09(TestClass01.java:71)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testMethod09 -->
</testsuite> <!-- TestCase003 -->
